int start_ced();
void stop_ced();
int clear_1401();
float square_wave(int div1,int div2, int div3);
float rate_gen(int div1,int div2, int div3);
float adc_setup(char *chan,int div1,int div2);
float adc_setup_trig(char *chan,int div1,int div2);
int ced_spool_update();
void down(short *d1,short *d2, int st,int sz);
void ced_stop_buffering();
void ced2file(char *s,int chan);
void adc_calib(int chan, char *name);
long a2d(int chan);
void d2a(int chan, float volt);
void trigger();
void setup_trigger();
long int get_count(long &c1, long &c2,long &c3);
float a2dcal(int chan);
float a2dcal_mem(int c, int nchan);
long a2d_mem(int c, int nchan, float &t);
long a2d_mem(int c, int nchan);
float a2dcal_mem(int c, int nchan, float &t);
double get_ctime();
void start_ctimer();
long *get_cederr();
void reset_ced_buff();
void reset_ced_update();
void d2acal(int c, float val);
void d2a_calib(int chan, char *name);
void ced2file_cyc(char *s,int chan);
void  ced2file_plus(char *s,int chan);
int start_cyc_ced();
void ced_string(char *s);
void dig_out(int val, int chan);
void set_dig_out_chan(int val);


void ced2file_b(char *s,int chan);
void ced2mat(matrix& tmp,int chan);
void ced2mat_plus(matrix& tmp,int chan);
