/*****************************************************************************/

#define BIOSKEY_SCRL         0x0010
#define BIOSKEY_NLCK         0x0020
#define BIOSKEY_CAPS         0x0040

#define BIOSKEY_SCANGET      0
#define BIOSKEY_SCANPEEK     1
#define BIOSKEY_SHIFT        2

#define BIOSKEY_RGTSHFT      0x0001
#define BIOSKEY_LFTSHFT      0x0002
#define BIOSKEY_LFTCTL       0x0004
#define BIOSKEY_LFTATL       0x0008

/*****************************************************************************/

#define KB_BACK    14
#define KB_ESC      1
#define KB_TAB     15
#define KB_BTAB   254
#define KB_SPACE   57
#define KB_ENTER   28

#define KB_F1      59
#define KB_F2      60
#define KB_F3      61
#define KB_F4      62
#define KB_F5      63
#define KB_F6      64
#define KB_F7      65
#define KB_F8      66
#define KB_F9      67
#define KB_F10     68

#define KB_SF1     84
#define KB_SF2     85
#define KB_SF3     86
#define KB_SF4     87
#define KB_SF5     88
#define KB_SF6     89
#define KB_SF7     90
#define KB_SF8     91
#define KB_SF9     92
#define KB_SF10    93

#define KB_CF1     94
#define KB_CF2     95
#define KB_CF3     96
#define KB_CF4     97
#define KB_CF5     98
#define KB_CF6     99
#define KB_CF7    100
#define KB_CF8    101
#define KB_CF9    102
#define KB_CF10   103

#define KB_AF1    104
#define KB_AF2    105
#define KB_AF3    106
#define KB_AF4    107
#define KB_AF5    108
#define KB_AF6    109
#define KB_AF7    110
#define KB_AF8    111
#define KB_AF9    112
#define KB_AF10   113

#define KB_HOME    71
#define KB_UP      72
#define KB_PGUP    73
#define KB_LEFT    75
#define KB_CENTRE  76
#define KB_RIGHT   77
#define KB_END     79
#define KB_DN      80
#define KB_PGDN    81

#define KB_CLEFT  115
#define KB_CRIGHT 116
#define KB_CUP    200
#define KB_CDN    201
#define KB_CEND   117
#define KB_CHOME  119
#define KB_CPGUP  132
#define KB_CPGDN  118

#define KB_INS     82
#define KB_DEL     83

#define KB_MINUS   74
#define KB_PLUS    78

#define KB_SLEFT  210
#define KB_SRIGHT 211
#define KB_SUP    212
#define KB_SDN    213

/*****************************************************************************/
